### ISSUE TITLE
When i use run with python3, ImportError occured 

### ISSUE THREAD

**Issue by evan-hwang** [strawberry-graphql/strawberry#3349]
ImportError : cannot import name 'GraphQLError' from 'graphql' 
## Describe the Bug
It works well when executed with poetry run app.main:main.
However, when executing with python3 app/main.py, the following Import Error occurs.

_**Error occured code line**_
<img width="849" alt="image" src="https://github.com/strawberry-graphql/strawberry/assets/10377550/713ab6b4-76c1-4b0d-84e1-80903f8855ea">

**_Traceback_**
```bash
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/evanhwang/dev/ai-hub/hub-api/app/bootstrap/admin/bootstrapper.py", line 4, in <module>
    from app.bootstrap.admin.router import AdminRouter
  File "/Users/evanhwang/dev/ai-hub/hub-api/app/bootstrap/admin/router.py", line 3, in <module>
    import strawberry
  File "/Users/evanhwang/Library/Caches/pypoetry/virtualenvs/hub-api-UM7sgzi1-py3.11/lib/python3.11/site-packages/strawberry/__init__.py", line 1, in <module>
    from . import experimental, federation, relay
  File "/Users/evanhwang/Library/Caches/pypoetry/virtualenvs/hub-api-UM7sgzi1-py3.11/lib/python3.11/site-packages/strawberry/federation/__init__.py", line 1, in <module>
    from .argument import argument
  File "/Users/evanhwang/Library/Caches/pypoetry/virtualenvs/hub-api-UM7sgzi1-py3.11/lib/python3.11/site-packages/strawberry/federation/argument.py", line 3, in <module>
    from strawberry.arguments import StrawberryArgumentAnnotation
  File "/Users/evanhwang/Library/Caches/pypoetry/virtualenvs/hub-api-UM7sgzi1-py3.11/lib/python3.11/site-packages/strawberry/arguments.py", line 18, in <module>
    from strawberry.annotation import StrawberryAnnotation
  File "/Users/evanhwang/Library/Caches/pypoetry/virtualenvs/hub-api-UM7sgzi1-py3.11/lib/python3.11/site-packages/strawberry/annotation.py", line 23, in <module>
    from strawberry.custom_scalar import ScalarDefinition
  File "/Users/evanhwang/Library/Caches/pypoetry/virtualenvs/hub-api-UM7sgzi1-py3.11/lib/python3.11/site-packages/strawberry/custom_scalar.py", line 19, in <module>
    from strawberry.exceptions import InvalidUnionTypeError
  File "/Users/evanhwang/Library/Caches/pypoetry/virtualenvs/hub-api-UM7sgzi1-py3.11/lib/python3.11/site-packages/strawberry/exceptions/__init__.py", line 6, in <module>
    from graphql import GraphQLError
ImportError: cannot import name 'GraphQLError' from 'graphql' (/Users/evanhwang/dev/ai-hub/hub-api/app/graphql/__init__.py)
```

## System Information
- Operating System: Mac Ventura 13.5.1(22G90)
- Strawberry Version (if applicable):
Entered in pyproject.toml as follows:
```bash
strawberry-graphql = {extras = ["debug-server", "fastapi"], version = "^0.217.1"}
```

**_pyproject.toml_**
```toml
##############################################################################
# poetry 종속성 설정
# - https://python-poetry.org/docs/managing-dependencies/#dependency-groups
# - 기본적으로 PyPI에서 종속성을 찾습니다.
##############################################################################
[tool.poetry.dependencies]
python = "3.11.*"
fastapi = "^0.103.2"
uvicorn = "^0.23.2"
poethepoet = "^0.24.0"
requests = "^2.31.0"
poetry = "^1.6.1"
sqlalchemy = "^2.0.22"
sentry-sdk = "^1.32.0"
pydantic-settings = "^2.0.3"
psycopg2-binary = "^2.9.9"
cryptography = "^41.0.4"
python-ulid = "^2.2.0"
ulid = "^1.1"
redis = "^5.0.1"
aiofiles = "^23.2.1"
pyyaml = "^6.0.1"
python-jose = "^3.3.0"
strawberry-graphql = {extras = ["debug-server", "fastapi"], version = "^0.217.1"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-mock = "^3.6.1"
httpx = "^0.24.1"
poetry = "^1.5.1"
sqlalchemy = "^2.0.22"
redis = "^5.0.1"
mypy = "^1.7.0"
types-aiofiles = "^23.2.0.0"
types-pyyaml = "^6.0.12.12"
commitizen = "^3.13.0"
black = "^23.3.0" # fortmatter
isort = "^5.12.0" # import 정렬
pycln = "^2.1.5" # unused import 정리
ruff = "^0.0.275" # linting

##############################################################################
# poethepoet
# - https://github.com/nat-n/poethepoet
# - poe를 통한 태스크 러너 설정
##############################################################################
types-requests = "^2.31.0.20240106"
pre-commit = "^3.6.0"


[tool.poe.tasks.format-check-only]
help = "Check without formatting with 'pycln', 'black', 'isort'."
sequence = [
    {cmd = "pycln --check ."},
    {cmd = "black --check ."},
    {cmd = "isort --check-only ."}
]

[tool.poe.tasks.format]
help = "Run formatter with 'pycln', 'black', 'isort'."
sequence = [
    {cmd = "pycln -a ."},
    {cmd = "black ."},
    {cmd = "isort ."}
]

[tool.poe.tasks.lint]
help = "Run linter with 'ruff'."
cmd = "ruff ."

[tool.poe.tasks.type-check]
help = "Run type checker with 'mypy'"
cmd = "mypy ."

[tool.poe.tasks.clean]
help = "Clean mypy_cache, pytest_cache, pycache..."
cmd = "rm -rf .coverage .mypy_cache .pytest_cache **/__pycache__"


##############################################################################
# isort
# - https://pycqa.github.io/isort/
# - python import 정렬 모듈 설정
##############################################################################
[tool.isort]
profile = "black"


##############################################################################
# ruff
# - https://github.com/astral-sh/ruff
# - Rust 기반 포맷터, 린터입니다.
##############################################################################
[tool.ruff]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    # "T20", # flake8-print
]
ignore = [
    "E501",  # line too long, handled by black
    "E402",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
]

[tool.commitizen]

##############################################################################
# mypy 설정
# - https://mypy.readthedocs.io/en/stable/
# - 정적 타입 체크를 수행합니다.
##############################################################################
[tool.mypy]
python_version = "3.11"
packages=["app"]
exclude=["tests"]
ignore_missing_imports = true
show_traceback = true
show_error_codes = true
disable_error_code="misc, attr-defined"
follow_imports="skip"

#strict = false

# 다음은 --strict에 포함된 여러 옵션들입니다.
warn_unused_configs = true  # mypy 설정에서 사용되지 않은 [mypy-<pattern>] config 섹션에 대해 경고를 발생시킵니다. (증분 모드를 끄려면 --no-incremental 사용 필요)
disallow_any_generics = false  # 명시적인 타입 매개변수를 지정하지 않은 제네릭 타입의 사용을 금지합니다. 예를 들어, 단순히 x: list와 같은 코드는 허용되지 않으며 항상 x: list[int]와 같이 명시적으로 작성해야 합니다.
disallow_subclassing_any = true  # 클래스가 Any 타입을 상속할 때 오류를 보고합니다. 이는 기본 클래스가 존재하지 않는 모듈에서 가져올 때( --ignore-missing-imports 사용 시) 또는 가져오기 문에 # type: ignore 주석이 있는 경우에 발생할 수 있습니다.
disallow_untyped_calls = true  # 타입 어노테이션이 없는 함수 정의에서 함수 호출시 오류를 보고합니다.
disallow_untyped_defs = false  # 타입 어노테이션이 없거나 불완전한 타입 어노테이션이 있는 함수 정의를 보고합니다. (--disallow-incomplete-defs의 상위 집합)
disallow_incomplete_defs = false  # 부분적으로 주석이 달린 함수 정의를 보고합니다. 그러나 완전히 주석이 달린 정의는 여전히 허용됩니다.
check_untyped_defs = true  # 타입 어노테이션이 없는 함수의 본문을 항상 타입 체크합니다. (기본적으로 주석이 없는 함수의 본문은 타입 체크되지 않습니다.) 모든 매개변수를 Any로 간주하고 항상 Any를 반환값으로 추정합니다.
disallow_untyped_decorators = true  # 타입 어노테이션이 없는 데코레이터를 사용할 때 오류를 보고합니다.
warn_redundant_casts = true  # 코드가 불필요한 캐스트를 사용하는 경우 오류를 보고합니다. 캐스트가 안전하게 제거될 수 있는 경우 경고가 발생합니다.
warn_unused_ignores = false  # 코드에 실제로 오류 메시지를 생성하지 않는 # type: ignore 주석이 있는 경우 경고를 발생시킵니다.
warn_return_any = false  # Any 타입을 반환하는 함수에 대해 경고를 발생시킵니다.
no_implicit_reexport = true  # 기본적으로 모듈에 가져온 값은 내보내진 것으로 간주되어 mypy는 다른 모듈에서 이를 가져오도록 허용합니다. 그러나 이 플래그를 사용하면 from-as를 사용하거나 __all__에 포함되지 않은 경우 내보내지 않도록 동작을 변경합니다.
strict_equality = true  # mypy는 기본적으로 42 == 'no'와 같은 항상 거짓인 비교를 허용합니다. 이 플래그를 사용하면 이러한 비교를 금지하고 비슷한 식별 및 컨테이너 확인을 보고합니다. (예: from typing import Text)
extra_checks = true  # 기술적으로는 올바르지만 실제 코드에서 불편할 수 있는 추가적인 검사를 활성화합니다. 특히 TypedDict 업데이트에서 부분 중첩을 금지하고 Concatenate를 통해 위치 전용 인자를 만듭니다.

# pydantic 플러그인 설정 하지 않으면 가짜 타입 오류 발생 여지 있음
# - https://www.twoistoomany.com/blog/2023/04/12/pydantic-mypy-plugin-in-pyproject/
plugins = ["pydantic.mypy", "strawberry.ext.mypy_plugin"]


##############################################################################
# 빌드 시스템 설정
##############################################################################
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


##############################################################################
# virtualenv 설정
# - 프로젝트에서 peotry 명령 호출 시 venv가 없다면 '.venv' 경로에 생성
##############################################################################
[virtualenvs]
create = true
in-project = true
path = ".venv"
```

## Additional Context
- I already run 'Invaidate Caches` in pycharm. 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3349">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3349/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3349/pledge.svg">
</picture>
</a>
