### ISSUE TITLE
pre-commit hook to generate schema.graphql

### ISSUE THREAD

**Issue by chrisemke** [strawberry-graphql/strawberry#3831]
## Feature Request Type

- [x] Alteration (enhancement/optimization) of existing feature(s)

## Description

My Idea is to have a git hook that can generate/re-generate the schema of the repo to be always updated, so if the dev change something on shema it will also have the schema updated automatically

**Comment by MarkusSagen** [comment]
You can add that pre-commit hook in your own projects in the `.pre-commit` file

**Comment by erikwrede** [comment]
Sounds cool, but I don't see us shipping hooks on the repo for now. However, this could be a cool addition to the docs section. @MarkusSagen are you interested in contributing your hook to the docs?

**Comment by thearchitector** [comment]
fwiw, i've done this for a while. this is the hook that i use to automatically re-gen my schema and include it in my current commit. feel free to add it to the docs if you'd like:

```yaml
  - repo: local
    hooks:
      - id: gen-gql-schema
        name: gen-gql-schema
        language: python
        entry: sh -c "strawberry export-schema lagoon.schema:GQL --output lagoon/schema/schema.graphql && git add lagoon/schema/schema.graphql"
        always_run: true
        pass_filenames: false
        require_serial: true
```
