### ISSUE TITLE
(dev server) support for Subscriptions requires `uvicorn[standard]` 

### ISSUE THREAD

**Issue by ossareh** [strawberry-graphql/strawberry#586]
To use `Subscription` websockets are required, to enable websockets you need to install `uvicorn[standard]`. Currently `pyproject.toml` / `poetry` is only installing `uvicorn`. Not having the "standard" extra results in a failure to upgrade the HTTP request to WebSocket, you can see this by increasing the uvicorn log_level in [`cli/commands/server.py`](https://github.com/strawberry-graphql/strawberry/blob/master/strawberry/cli/commands/server.py#L43) and attempting a Subscription.

I see two paths to improving this situation, I'm happy to submit a PR for either route - but I need advice on how to proceed 👍 

_Option 1: update dependencies in pyproject.toml_

Changing the [`uvicorn` dependency](https://github.com/strawberry-graphql/strawberry/blob/master/pyproject.toml#L27) to be `{version = ">=0.11.6,<0.13.0", extras = ["standard"]}` would result in websockets being supported. However as per [Uvicorn's QuickStart](https://www.uvicorn.org/#quickstart) that brings in Cython dependencies which may not be what folks want.

_Option 2: improve documentation to mention this requirement_

The safe route, at the risk of a bit more work for the user. It's likely that any "real" deployment would have folks needing to be a bit more opinionated about the way they run their ASGI sever.

**Comment by BryceBeagle** [comment]
Can we create an `extras` group that includes `uvicorn[standard]`? Does poetry support this?

```toml
[tool.poetry.dependencies]
uvicorn = ">=0.11.6,<0.13.0"
uvicorn_standard = { version = ">=0.11.6,<0.13.0", extras = ["standard"], optional = true }

[tool.poetry.extras]
subscriptions = ["uvicorn_standard"]
```

I agree that better documentation is needed regardless.
